import React, { PureComponent } from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import Container from 'libraries/components/AuthTemplate/Airbnb/components/Container';
import Header from 'libraries/components/Header';
import ContentPrivacy from './ContentPrivacy';


class PrivacyPolicy extends PureComponent {
    render() {
        return (
            <Container>
                <Header
                    back
                    text='Privacy Policy'
                />
                <ScrollView>
                    <View style={styles.wrapper}>
                        <Text style={styles.textStyle}>
                            Effective date: April 27, 2019
                        </Text>
                        <Text style={styles.textStyle}>
                            Unfollow & Clean Mass ("us", "we", or "our") operates the Unfollow & Clean Mass mobile application (hereinafter referred to as the "Service").
                        </Text>
                        <Text style={styles.textStyle}>
                            This page informs you of our policies regarding the collection, use,
                            and disclosure of personal data when you use our Service and the choices you have associated with that data.
                            We use your data to provide and improve the Service.
                            By using the Service, you agree to the collection and use of information in accordance with this policy.
                            Unless otherwise defined in this Privacy Policy,
                            the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                        </Text>
                        <Text style={styles.titleStyle}>Definitions</Text>
                        <ContentPrivacy
                            textContent 
                            title='Service'
                            content='Service is the Unfollow & Clean Mass mobile application operated by Unfollow & Clean Mass'
                        />
                        <ContentPrivacy
                            textContent 
                            title='Personal Data'
                            content='Personal Data means data about a living individual who can be identified from those 
                            data (or from those and other information either in our possession or likely to come into our possession).'
                        />
                        <ContentPrivacy
                            textContent 
                            title='Usage Data'
                            content='Usage Data is data collected automatically either generated by the use of the 
                            Service or from the Service infrastructure itself (for example, the duration of a page visit).'
                        />
                        <ContentPrivacy
                            textContent 
                            title='Cookies'
                            content='Cookies are small files stored on your device (computer or mobile device).'
                        />

                        <Text style={styles.titleStyle}>Information Collection and Use</Text>
                        <Text style={styles.textStyle}>
                            We collect several different types of information for various purposes to provide and improve our Service to you.
                        </Text>
                        <Text style={styles.TypeStyle}>Types of Data Collected</Text>
                        <Text style={styles.PersonalStyle}>Personal Data</Text>
                        <Text style={styles.textStyle}>
                            While using our Service, we may ask you to provide us with certain personally identifiable 
                            information that can be used to contact or identify you ("Personal Data"). 
                            Personally identifiable information may include, but is not limited to:
                        </Text>

                        <ContentPrivacy
                            title='Email address'
                        />
                        <ContentPrivacy
                            title='Cookies and Usage Data'
                        />

                    </View>
                </ScrollView>
            </Container>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1
    },
    wrapper: {
        flex: 1,
        backgroundColor: '#FFF',
        paddingHorizontal: 10,
        paddingVertical: 15,
    },
    textStyle: {
        fontSize: 14,
        color: '#000',
        paddingTop: 5,
    },
    titleStyle: {
        fontSize: 18,
        fontWeight: '500',
        color: '#000',
        paddingTop: 10
    },
    TypeStyle: {
        fontSize: 17,
        fontWeight: '500',
        color: '#000',
        paddingTop: 5
    },
    PersonalStyle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#444',
        paddingTop: 5
    }
})
export default PrivacyPolicy;